### ISSUE TITLE
Can I help you translation into chinese ?

### ISSUE THREAD

**Issue by tu6ge** [wearebraid/vueformulate.com#104]
I know you is coding for Vue3 . and can I help you translation documents of `version 2.5` into chinese ?

**Comment by justin-schroeder** [comment]
Yes — Please do! https://vueformulate.com/guide/contributing/

**Comment by justin-schroeder** [comment]
@tu6ge do you mean the documentation itself or the messages? If you'd like to help with the docs that would be incredible — although your effort might be better spent on the version 3 of the docs.

**Comment by tu6ge** [comment]
I believe vue2 will last a long time in my country. and I also translate vue3

**Comment by tu6ge** [comment]
In fact, I spend more time translating documents with tools.

**Comment by justin-schroeder** [comment]
@tu6ge awesome work — I'll send you an email about what we're working on 👀
