### ISSUE TITLE
Outdated documentation on registering custom input type

### ISSUE THREAD

**Issue by ceilfors** [wearebraid/vueformulate.com#105]
The documentation is outlined at https://vueformulate.com/guide/inputs/custom-inputs/#registering-an-input is showing the usage of 

```
Vue.use(VueFormulate, {
  library: {
    autocomplete: {
      classification: 'text',
      component: 'MyFormulateAutocomplete'
    }
  }
})
```

Where I can see that the correct usage now is actually the plugin approach:

```
export default function (formulateInstance) {
  formulateInstance.extend({
    components: {
      MyFormulateAutocomplete
    },
    library: {
      autocomplete: {
        classification: 'text',
        component: 'MyFormulateAutocomplete'
      }
    }
  })
}
```

**Comment by justin-schroeder** [comment]
Howdy! You do not have to write that as a plugin, most people choose to just register them directly during registration. The plugin approach is also valid, but the first example is not incorrect or deprecated.

**Comment by ceilfors** [comment]
Howdy @justin-schroeder! I regret not capturing more context in this issue, but I vaguely remembered that I spent hours troubleshooting why the first example is not working and ended up scouring through the innards of the documentation to make this work. Feel free to close if I got it wrong though. Thanks for maintaining this awesome library.

**Comment by justin-schroeder** [comment]
OK! Sorry you spent that time :( If this crops up again as an issue for you we'll take another look!
