### ISSUE TITLE
Clicking on a checkbox or radio button causes the form to disappear on the documentation site

### ISSUE THREAD

**Issue by apotheosis91** [wearebraid/vueformulate.com#85]
Firstly, I would like to thank you for the awesome Vue Formulate! It is really powerful!

I found a little bug on documentation site, when you click on any checkbox or radio button the corresponding form disappears (see gif below). Tested in Chrome and Firefox. OS - Windows 10.

![recording](https://user-images.githubusercontent.com/9337323/112311456-67e21500-8cae-11eb-97c2-087e9c9ce5b8.gif)

I think it is because of the `overflow: hidden` and `flex-direction: row-reverse` on the `.preview-code` element (see second gif), but I could be wrong.

![recording (1)](https://user-images.githubusercontent.com/9337323/112311703-abd51a00-8cae-11eb-9b5f-70e4e52f39f7.gif)

**Comment by sidizawi** [comment]
Hi, I worked on it, and I created a [PR](https://github.com/wearebraid/vueformulate.com/pull/106)

**Comment by justin-schroeder** [comment]
I believe this is fixed now. Thanks!
